source = '''
211p&01p>121p          >21g1+21p 11g21g-v>11g21g%#v_v
                                        >|
                 v,,,,, ,,,.g11"is prime"<
>       ^        >   v ^                          <
^_@#-g10p11:+1g11,*25<,,,,,,,,,,,,.g11"is not prime"<
'''
width = 53
height = 5
input = ['25']
name = "Calculating Prime Numbers"
